# Generated by Django 2.0.7 on 2018-08-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
    ]
